name: Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-commit-pdf:
    if: "contains(github.event.head_commit.message, '[skip ci]') == false"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        run: |
          echo "changed-files=$(git diff-tree --no-commit-id --name-only -r HEAD | xargs)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        if: |
          contains(steps.changed-files.outputs.changed-files, 'src/content/resume/') ||
          contains(steps.changed-files.outputs.changed-files, 'scripts/generate-resume.js')
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        if: |
          contains(steps.changed-files.outputs.changed-files, 'src/content/resume/') ||
          contains(steps.changed-files.outputs.changed-files, 'scripts/generate-resume.js')
        run: npm install

      - name: Generate resume PDF
        if: |
          contains(steps.changed-files.outputs.changed-files, 'src/content/resume/') ||
          contains(steps.changed-files.outputs.changed-files, 'scripts/generate-resume.js')
        run: npm run pdf

      - name: Commit and push if changed
        if: |
          contains(steps.changed-files.outputs.changed-files, 'src/content/resume/') ||
          contains(steps.changed-files.outputs.changed-files, 'scripts/generate-resume.js')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update resume.pdf [skip ci]"
          file_pattern: "public/resume.pdf"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"

  build-and-deploy-site:
    needs: build-and-commit-pdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest master
        uses: actions/checkout@v4
        with:
          ref: 'master'
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install, build, and upload your site
        uses: withastro/action@v2

  deploy:
    needs: build-and-deploy-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
